Permissions:
  AdvancedEggHuntCommandPermission: advancedegghunt.main
  BreakEggPermission: advancedegghunt.break
  PlaceEggPermission: advancedegghunt.place

Settings:
  SoundVolume: 3
  Updater: true
  PlayerFoundOneEggRewards: true
  PlayerFoundAllEggsReward: true
  DisableCommandFeedback: true
  ShowCoordinatesWhenEggFoundInProgressInventory: false
  ArmorstandGlow: 10
  RewardInventoryMaterial: PAPER

Sounds:
  PlayerFindEggSound: ENTITY_PLAYER_LEVELUP
  EggAlreadyFoundSound: ENTITY_VILLAGER_NO
  AllEggsFoundSound: ENTITY_ENDER_DRAGON_DEATH
  EggBreakSound: BLOCK_NOTE_BLOCK_BASS
  EggPlaceSound: BLOCK_NOTE_BLOCK_BELL
  ErrorSound: BLOCK_NOTE_BLOCK_BASEDRUM
  InventoryClickSuccess: BLOCK_NOTE_BLOCK_CHIME
  InventoryClickFailed: BLOCK_NOTE_BLOCK_HAT

Rewards:
  #types: 0 = Player found one egg; 1 = Player found all eggs
    0:
      command: 'tellraw %PLAYER% "%PREFIX%&aYou found a egg. &7(&e%EGGS_FOUND%&7/&e%EGGS_MAX%&7)"'
      enabled: true
      type: 0
    1:
      command: 'give %PLAYER% diamond'
      enabled: true
      type: 0
    2:
      command: 'tellraw %PLAYER% "%PREFIX%&aYou found a egg. &7(&e%EGGS_FOUND%&7/&e%EGGS_MAX%&7)"'
      enabled: true
      type: 1
    3:
      command: 'give %PLAYER% diamond'
      enabled: true
      type: 1
    4:
      command: 'tellraw %PLAYER% "%PREFIX%&6You found all eggs!"'
      enabled: true
      type: 1