Permissions:
  AdvancedEggHuntCommandPermission: advancedegghunt.main
  BreakEggPermission: advancedegghunt.break
  PlaceEggPermission: advancedegghunt.place

Settings:
  ItemInEggList: PAPER
  SoundVolume: 3

Sounds:
  PlayerFindEggSound: ENTITY_PLAYER_LEVELUP
  EggAlreadyFoundSound: ENTITY_VILLAGER_NO
  AllEggsFoundSound: ENTITY_ENDER_DRAGON_DEATH
  EggBreakSound: BLOCK_NOTE_BLOCK_BASS
  EggPlaceSound: BLOCK_NOTE_BLOCK_BELL
  ErrorSound: BLOCK_NOTE_BLOCK_BASEDRUM