name: AdvancedEggHunt
version: 1.8
main: de.theredend2000.advancedegghunt.Main
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  advancedegghunt:
    aliases:
      - aeh
      - advancedhunt
      - egghunt
      - eggs
      - easter
